/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.70"

    // Apply the application plugin to add support for building a CLI application.
    application
}

val ktor_version = "1.3.2"

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    implementation("org.ow2.asm:asm:6.0")
    implementation("org.ow2.asm:asm-commons:6.0")

   // // use the ktor
   // implementation("io.ktor:ktor-io:$ktor_version")
   // implementation("io.ktor:ktor-client-cio:$ktor_version")
}

application {
    // Define the main class for the application.
    mainClassName = "com.anatawa12.dtsGenerator.AppKt"
}

tasks {
    run.invoke {
        args = listOf(
                "../minecraft.d.ts",

                "only:str:org/ietf/jgss/",
                "only:str:org/omg/",
                "only:str:java/",
                "only:str:javax/",
                "jar:file:jvm-home:lib/rt.jar",

                "always:",
                "only:str:java/util/",
                "only:str:java/lang/reflect/",
                "jar:file:jvm-home:lib/rt.jar",

    //            "always:",
    //            "only:str:jp/ngt/rtm/",
    //            "exclude:str:jp/ngt/rtm/gui",
    //            "exclude:str:jp/ngt/rtm/command",
    //            "exclude:str:jp/ngt/rtm/modelpack/init",
    //            "exclude:str:jp/ngt/rtm/network",
    //            "comment:str:rtm 1.12.2",
    //            "jar:get:get:str:https://addons-ecs.forgesvc.net/api/v2/addon/288988/file/2934639/download-url",

                "always:",
                "only:str:jp/ngt/ngtlib/io",
                "comment:str:rtm 1.12.2",
                "jar:get:get:str:https://addons-ecs.forgesvc.net/api/v2/addon/288989/file/2934633/download-url",

                "always:",
                "only:str:net/minecraft/block/",
                "only:str:net/minecraft/entity/",
                "only:str:net/minecraft/item/",
                "only:str:net/minecraft/nbt/",
                "only:str:net/minecraft/tileentity/",
                "only:str:net/minecraft/util/",
                "only:str:net/minecraft/world/",
                "exclude:str:net/minecraft/world/storage",
                "comment:str:minecraft 1.12.2 with srg by forge",
                "srg:zip:get:str:http://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp/1.12.2/mcp-1.12.2-srg.zip!joined.srg",
                "mcp:zip:get:str:http://export.mcpbot.bspk.rs/mcp_stable/39-1.12/mcp_stable-39-1.12.zip!fields.csv",
                "mcp:zip:get:str:http://export.mcpbot.bspk.rs/mcp_stable/39-1.12/mcp_stable-39-1.12.zip!methods.csv",
                "sig:str:net/minecraft/util/IObjectIntIterable!<V:Ljava/lang/Object;>Ljava/lang/Object;Ljava/lang/Iterable<TV;>;",
                "jar:get:str:https://launcher.mojang.com/v1/objects/0f275bc1547d01fa5f56ba34bdc87d981ee12daf/client.jar",

                "always:",
                "only:str:net/minecraft/block/",
                "only:str:net/minecraft/entity/",
                "only:str:net/minecraft/item/",
                "only:str:net/minecraft/nbt/",
                "only:str:net/minecraft/tileentity/",
                "only:str:net/minecraft/util/",
                "only:str:net/minecraft/world/",
                "exclude:str:net/minecraft/world/storage",
                "comment:str:minecraft 1.7.10 with srg by forge",
                "srg:zip:get:str:http://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp/1.7.10/mcp-1.7.10-srg.zip!joined.srg",
                "mcp:zip:get:str:http://export.mcpbot.bspk.rs/mcp_stable/12-1.7.10/mcp_stable-12-1.7.10.zip!fields.csv",
                "mcp:zip:get:str:http://export.mcpbot.bspk.rs/mcp_stable/12-1.7.10/mcp_stable-12-1.7.10.zip!methods.csv",
                "jar:get:str:https://launcher.mojang.com/v1/objects/e80d9b3bf5085002218d4be59e668bac718abbc6/client.jar",

    //            "comment:str:forge 1.12.2",
    //            "srg:zip:get:str:http://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp/1.12.2/mcp-1.12.2-srg.zip!joined.srg",
    //            "jar:get:str:https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-universal.jar",

                "jar:get:str:https://libraries.minecraft.net/com/google/guava/guava/21.0/guava-21.0.jar",

                "exclude:str:com/google/gson/internal/",
                "jar:get:str:https://libraries.minecraft.net/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar"
        )
    }
}
